# Generated by Django 3.2.7 on 2021-09-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('prefecture', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=100)),
            ],
        ),
    ]
